//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicatieDisertatie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        public int InstitutionID { get; set; }
        public string InstitutionName { get; set; }
        public string InstitutionAddress { get; set; }
        public Nullable<int> InstitutionPhoneNumber { get; set; }
        public string InstitutionEmailAddress { get; set; }
    }
}
