//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicatieDisertatie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutionProgram
    {
        public int InstitutionProgramID { get; set; }
        public int InstitutionID { get; set; }
        public string InstitutionProgram1 { get; set; }
    }
}
