//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicatieDisertatie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseFile
    {
        public int ResponseFileId { get; set; }
        public string UserId { get; set; }
        public int FileId { get; set; }
        public string File { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual File File_Response { get; set; }
    }
}
