//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicatieDisertatie.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAnswer
    {
        public string UserId { get; set; }
        public int OptionId { get; set; }
        public string Text { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual QuestionOption QuestionOption { get; set; }
    }
}
